Changed to static versioning
This line did not work when trying to pip install this library as a local folder, produced error AttributeError: 'NoneType' object has no attribute 'split'